# Generated by Django 4.1.7 on 2023-04-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_remove_positiondb_age_positiondb_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='playerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerposition', models.CharField(blank=True, max_length=100, null=True)),
                ('playername', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('club', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='productimage')),
            ],
        ),
    ]
